/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * analizadorlexico.java
 *
 * Created on 05-jun-2018, 12:32:08
 */

package alexico;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import java_cup.runtime.Symbol;

/**
 *
 * @author gabinopc
 */
public class analizador extends javax.swing.JFrame {

    /** Creates new form analizadorlexico */
    public analizador() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        frmFuente = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        frmLexico = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        frmSintactico = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        frmRes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        frmFuente.setColumns(20);
        frmFuente.setRows(5);
        jScrollPane1.setViewportView(frmFuente);

        frmLexico.setColumns(20);
        frmLexico.setRows(5);
        jScrollPane2.setViewportView(frmLexico);

        jButton1.setText("ANÁLISIS LÉXICO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("CÓDIGO FUENTE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("ANÁLISIS LÉXICO SINTÁCTICO");

        jButton2.setText("ANÁLISIS SINTÁCTICO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        frmSintactico.setColumns(20);
        frmSintactico.setRows(5);
        jScrollPane3.setViewportView(frmSintactico);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("RESULTADO:");

        frmRes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton2)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(frmRes, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(frmRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            AnalisisLexico();
        } catch (IOException ex) {
            Logger.getLogger(analizador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String codigo=frmFuente.getText();
        Sintac sint = new Sintac(new LexicoCup(new StringReader(codigo)));
        try {
            sint.parse();
            frmSintactico.setText("Analisis correcto");
            frmRes.setText(sint.action_obj.resultado);
        } catch (Exception ex) {
            Symbol sym=sint.getS();            
            frmSintactico.setText("Error: Linea: "+(sym.right+1)+" Columna: "+(sym.left+1)+" texto: "+sym.value);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new analizador().setVisible(true);
            }
        });
    }

    public void AnalisisLexico() throws IOException{
        int con=1;
        String fuente = (String) frmFuente.getText();
        Lexico lexico = new Lexico(new StringReader(fuente));
        String res = "LINEA: " + con + "\t\tSIMBOLO\n";
        while (true){
            Token token = lexico.yylex();
            if (token==null){
                frmLexico.setText(res);
                return;
            } 
            switch(token){
                case LINEA:
                    con++;
                    res+="LINEA:" + con + "\n";
                    break;
                case IF:
                    res+="<Reservado int>\t" + lexico.lexeme + "\n";
                    break;
                case ELSE:
                    res+="<Reservado else>\t" + lexico.lexeme + "\n";
                    break;
                case WHILE:
                    res+="<Reservado while>\t" + lexico.lexeme + "\n";
                    break;
                case EQUALS:
                    res+="<Operador comparacion>\t" + lexico.lexeme + "\n";
                    break;
                case ASSIGN:
                    res+="<Operador igual>\t" + lexico.lexeme + "\n";
                    break;
                case PLUS:
                    res+="<Operador suma>\t" + lexico.lexeme + "\n";
                    break;
                case MINUS:
                    res+="<Operador resta>\t" + lexico.lexeme + "\n";
                    break;
                case TIMES:
                    res+="<Operador multiplicacion>\t" + lexico.lexeme + "\n";
                    break;
                case DEVIDED:
                    res+="<Operador division>\t" + lexico.lexeme + "\n";
                    break;
                case PARA:
                    res+="<Paréntesis de apertura>\t" + lexico.lexeme + "\n";
                    break;
                case PARC:
                    res+="<Paréntesis de cierre>\t" + lexico.lexeme + "\n";
                    break;
                case LLAA:
                    res+="<Llave de apertura>\t" + lexico.lexeme + "\n";
                    break;
                case LLAC:
                    res+="<Llave de cierre>\t" + lexico.lexeme + "\n";
                    break;
                case MAIN:
                    res+="<Reservado main>\t" + lexico.lexeme + "\n";
                    break;                    
                case PUNTOC:
                    res+="<Punto y coma>\t" + lexico.lexeme + "\n";
                    break;
                case ID:
                    res+="<Identificador>\t" + lexico.lexeme + "\n";
                    break;
                case NUMERO:
                    res+="<numero>\t" + lexico.lexeme + "\n";
                    break;
                case ERROR:
                    res+="<Símbolo no definido>\n";
                    break;
                default:
                    res+= " < " + lexico.lexeme + ">\n";
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea frmFuente;
    private javax.swing.JTextArea frmLexico;
    private javax.swing.JTextField frmRes;
    private javax.swing.JTextArea frmSintactico;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

}