
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Dec 30 11:43:08 COT 2019
//----------------------------------------------------

package alexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 10;
  public static final int LLAC = 15;
  public static final int ELSE = 4;
  public static final int LLAA = 14;
  public static final int PLUS = 8;
  public static final int INT = 2;
  public static final int WHILE = 5;
  public static final int PARC = 13;
  public static final int IF = 3;
  public static final int ID = 18;
  public static final int PARA = 12;
  public static final int DEVIDED = 11;
  public static final int EQUALS = 7;
  public static final int EOF = 0;
  public static final int MAIN = 16;
  public static final int PUNTOC = 17;
  public static final int MINUS = 9;
  public static final int NUMERO = 19;
  public static final int ERROR = 1;
  public static final int ASSIGN = 6;
}

